version: 2.1
jobs:
  build:
    docker:
    - image: docker:stable
    environment:
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.8
    - run: docker buildx ls
    - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7 \
          --output "type=image,push=true" \
          --tag stoub/nav-ui:latest \
          --file ./Dockerfile ./
