version: 2.1
jobs:
  build:
    docker:
    - image: docker:stable
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run: apk add make curl
    - run: mkdir -vp ~/.docker/cli-plugins/
    - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64
    - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
    - run: docker buildx ls
    - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7 \
          --output "type=image,push=true" \
          --tag stoub/nav-ui:latest \
          --file ./Dockerfile ./
